### PR TITLE
Allow unbounded ranges

### PR DESCRIPTION
**Pull request by gavinwahl**
https://www.postgresql.org/docs/devel/static/rangetypes.html#RANGETYPES-INFINITE

### CODE REVIEW

**Comment by yigitguler** [comment]
Hi @gavinwahl, thank you for the contribution!

What if the user of this library wants to avoid infinite range types, how should he determine this?

**Comment by gavinwahl** [comment]
I would recommend defining a validation method, as you would use to restrict any other type of field.

**Comment by alicertel** [comment]
Hi @gavinwahl, thank you for the contribution!

Clearly not allowing null values doesn't fit everybody's need. Same applies for allowing null.

@yigitguler @gavinwahl  How about adding `child_attrs` attribute to the RangeField to define behaviours of the child field. That way allowing null or not can be customizable. This would also be backward compatible.

Sample usage: IntegerRangeField(child_attrs={"allow_null":True, "validators":,....}  )

**Comment by yigitguler** [comment]
@alicertel sounds good to me.

**Comment by alicertel** [comment]
Closing the Pr since there is no progress.

**Pull request closed without merging**
