### PR TITLE
SerializablePKRelatedField

### PR DESCRIPTION
**Pull request by KhasanovBI**
Field that take primary key as internal value, and represented by some serializer.

### CODE REVIEW

**Comment by KhasanovBI** [comment]
In my work in many cases we need pass to serializer in data primary keys, but have a represent of this field.
For example, we have one endpoint, where we are looking for people, and second endpoint where we create something, where there is a queue of people, where we specify the id of people, we don't create an object, so I do a field that take primary key as internal value, and represented by some serializer.

**Comment by KhasanovBI** [comment]
What's is the difference with PresentablePrimaryKeyRelatedField?
1. It has a correct name, Tom Christie named his fields: StringRelatedField, HyperlinkedRelatedField, SlugRelatedField, PrimaryKeyRelatedField. RelatedField - means that it take Foreignkey as internal_value, and prefix show what we have when represent object.
2. In case of many=True, we don't create a lot of instances, we create only one, performance is better.
3. You don't need to pass queryset, if you pass ModelSerializer.
4. A lot of tests.
PS. Some my ideas about context and assertions considered too.

**Comment by alicertel** [comment]
Hi @KhasanovBI ,
Thank you for your contributions.

I have some comments about your thoughts.

1 -  The name `SerializableRelatedField ` is too generic. In fact all of the `RelatedField`s are `serializable`. 

`PrimaryKeyRelatedField` takes `pk` as data, `SlugRelatedField` takes `slug` as data ... That's the way how they named. They use `pk` or `slug` to make a query and get the object.  `SerializableRelatedField `  takes `pk` as data. So it's in fact works like `PrimaryKeyRelatedField` but the way they represented is different. 

I would not name it as `SerializableRelatedField`. There is no way to understand it uses `pk` to retrieve the object.

2 - How is this different than other related fields? https://github.com/Hipo/drf-extra-fields/pull/23/files#diff-c00c8fa4b372409f5e72b508ae17f35dR190  Here it makes a query for each item in the list. Did i miss something?

3 - `Explicit is better than implicit`. I would definitely force developers to provide a queryset. But if you are getting the model from provided serializer and preparing the queryset, you should use default manager. https://github.com/Hipo/drf-extra-fields/pull/23/files#diff-c00c8fa4b372409f5e72b508ae17f35dR184  Here it uses `objects`. 

4 -  `PresentablePrimaryKeyRelatedField` extends the `PrimaryKeyRelatedField` and overrides `to_representation` method. So it only need tests for that method. Rest is handled by DRF itself. I trust Tom on this:P

**Comment by KhasanovBI** [comment]
Hi, @alicertel , thanks to you for discussions, If we not talking, we would not have improve this field)

1. You're wrong. All RelatedFields takes pk as data. But SlugRelatedField return slug, PrimaryKeyRelatedField return pk, HyperlinkedRelatedField return hyperlink, look at [this](http://www.django-rest-framework.org/api-guide/relations/#hyperlinkedrelatedfield) and etc. SerializableRelatedField return serialized object - not just one entity like string(in case of SlugRelatedField, HyperlinkedRelatedField) or integer(in case of PrimaryKeyRelatedField). Prefix say what we have in representation. It's return a serialized structure. PresentablePrimaryKeyRelatedField doesn't return PresentablePrimaryKey it return serialized structure, so i think, it's a not good name.

2. It's not for representation of object, it's made to valid if related field with this pk exists or not. Look at [source code of PrimaryKeyRelatedField](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/relations.py#L219). It's done analogical, but without `pk_field` checking.

3. I don't think, that it's right place for this idiom, because in use default behaviour that I'm write in docs, and if you pass ModelSerializer in some cases there is no need to pass queryset, because you know model of ModelSerializer, if you want to pass special queryset, you can pass queryset, and if you want with special manager.

4. Extending from PrimaryKeyRelatedField is bad, because it can take `pk_field` argument, that represent object, [look at the docs](http://www.django-rest-framework.org/api-guide/relations/#primarykeyrelatedfield), but you don't use it in PresentablePrimaryKeyRelatedField.

Thanks for the comments.

**Comment by alicertel** [comment]
1 - The way that `slug_field` on SlugRelatedField, and `pk_field` on `PrimaryKeyRelatedField` are totaly different.
From docs.
>**slug_field** - The field on the target that should be used to represent it. This should be a field that uniquely identifies any given instance. For example, username. required.

> **pk_field** - Set to a field to control **serialization/deserialization** of the primary key's value. For example, **pk_field=UUIDField(format='hex')** would serialize a UUID primary key into its compact hex representation.

pk_field on PKRelatedField is used for **serialization**. Here It's crystal clear that we do serialize/deserialize the fields already.

[Here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/relations.py#L410) You can see slug_field used to retrieve the object. That's why it's named as `SlugRelatedField` and does not user `pk` to retrieve the object.

2 -  
>In case of many=True, we don't create a lot of instances, we create only one, performance is better.

You do create a lot of instances.
 
Please see my comments about pk_field on 4.

3- This is a subjective topic. Both approaches can be used. I told u what would be mine.

4- `pk_field` is used in `to_internal_value` method. But we do not use it in `to_represantation`. Because we want to change the way it serialized. That's why `presentation_serializer` is required.

There is no point of using it in  `to_represantation`.

**Comment by KhasanovBI** [comment]
1 - 

> In fact all of the RelatedFields are serializable.

In fact all of the RelatedFields are presentable. =)
2 - [in this place](https://github.com/Hipo/drf-extra-fields/blob/462212c06f2f10113d7ab98a74c3aecc3deb26df/drf_extra_fields/relations.py#L28) in case of [many=True](https://github.com/tomchristie/django-rest-framework/blob/67ac0486f504d957fd123c8b913fb93a71cacdcd/rest_framework/serializers.py#L618) you create a lot of instances.
3 - so, close this question)
4 - Agree with you.

**Comment by alicertel** [comment]
1- Ahah fair enough :) It should be `SomethingPrimaryKeyRelatedField`. `PrimaryRelatedField` is a good name but it's already exists in DRF. So one should come up with a better name. I will leave it to the maintainers of the project.
2- `SerializedRelatedField` does it too. This is your statement. 
> In case of many=True, we don't create a lot of instances, we create only one, performance is better.

So there is no performance gain in `SerializedRelatedField`

What is wrong in `SerializedRelatedField`?
- It has  a lot of redundant tests. Those tests are already exists in DRF. 
- It works like `PrimaryKeyRelatedField`. It should extend it without touching `to_internal_value`.

I am not gonna dive into naming :)

**Comment by KhasanovBI** [comment]
For each child ListSerializer call to_representation method, and every time you create serializer instance and call data.

**Comment by alicertel** [comment]
Ahh. I finally got your point. I was always thinking the db calls when you say performance. Didn't even think about.

But you also create instance of the serializer even though you don't use it in all cases. If we are talking about micro level performance issues here i go :)

https://github.com/Hipo/drf-extra-fields/pull/23/files#diff-c00c8fa4b372409f5e72b508ae17f35dR186 Here you create an instance of given serializer and this serializer only used in `to_representation`. So if you don't use the `to_representation` you will have an instance of the given serializer even thought you don't need it.

**Comment by KhasanovBI** [comment]
@alicertel I think that micro bad word to describe the performance in the programming language level, in many cases, programming errors can slow down the program significantly. How will you use `cached_property` in this case? I think in this case it can not be used, it is necessary to save the results of long calculations.

**Comment by dyus** [comment]
What about this pr? SerializablePKRelatedField looks nice

**Comment by yigitguler** [comment]
Hi, Per discussion on the other PR, we decided to merge other implementation. Thanks @KhasanovBI for mind opening discussion.

**Pull request closed without merging**
