### PR TITLE
Generic relations, UUID support, parameterized serializers, and serializer based formats

### PR DESCRIPTION
**Pull request by rpatterson**
This PR includes a number of different DRF extensions I needed while developing support for 2 different JSON-based formats and are more generally applicable than just those formats:

- Support for serializing Django generic relations including a model serializer base class that will automatically use the field for a model's generic relations
- Support for using UUID's throughout an API while still using integer PK IDs in the DB
- Parameterized serializers that lookup a specific serializer based on a parameter, such as a `type` field.  Useful for generic endpoints that can represent multiple different types of resources, among other uses.
- Support for renderers/parsers/formats that use a serializer to define and process the format.  Useful for defining more highly structured formats best expressed under DRF in terms of serializers.

All contributions have full test coverage.  This PR also includes some tox/CI improvements as well as some pep8 cleanup.

### CODE REVIEW

**Comment by rpatterson** [comment]
The above failure is related to GDAL and isn't related to my changes.

**Comment by rpatterson** [comment]
Fixed the GDAL Travis CI errors

**Comment by yigitguler** [comment]
Thanks for the PR. We will review and get back to you.

**Comment by rpatterson** [comment]
Just a quick check-in.  Do you think it will be very long before y'all can review this?  I totally understand, not having the time, just wanted to get a sense of timeline.  Thanks!

**Comment by yigitguler** [comment]
Hi @rpatterson,

We were in a team event. We are planning to review within this week.

Regards

**Comment by alicertel** [comment]
Hi @rpatterson ,

Thanks for your contribution. 

Can you update your branch with the master please?. I merged some open PR's. Looks like there are some conflicts.

Also can you revert your pep8 fixes please? We do follow all pep8 rules except a few. For example max character length is 120 not 80 in the project. 

I will continue reviewing you changes early next week.

@yigitguler Maybe we should prepare a style guide.

**Comment by alicertel** [comment]
I setup a flake8 which allows max-line-lenght to be 120. Sorry for being late for coding style standart.

**Comment by rpatterson** [comment]
K, pulled in `Hipo/master` and addressed all the issues, @alicertel.  LMK if there's anything more I can do to help?

**Comment by alicertel** [comment]
Hi @rpatterson ,
I tried to review the pr a few times. But it's really difficult to review such a big PR. I couldn't understand some of the fields. if you are still interested in adding new fields could you please open an issue about this new fields explaining their use cases?

Please let me know your thoughts on this.

**Pull request closed without merging**
