### PR TITLE
support Django 3.0

### LINKED ISSUE #115: Import error on Django 3.0
Django 3.0 has removed `django.utils.six`. As we are still using `six.text_type` and `six.string_types`, the imports fail.

### PR DESCRIPTION
**Pull request by kozlek**
Fix #115 by moving `text_type` and `string_types` imports in the `compat` module.

### CODE REVIEW

**Comment by lucacorti** [comment]
Travis seems to break because of GDAL version, maybe `dist: bionic` in `.travis.yml`could help?

**Comment by kozlek** [comment]
> Travis seems to break because of GDAL version, maybe `dist: bionic` in `.travis.yml`could help?

Yes you are right 🙂
Xenial ships GDAL 1.11.3 but Django 3.0 requires >= 2.0.
However, Bionic ships GDAL 2.2.3 which is not supported by Django 1.11, the last version available for Python 2.7.
We may have to choose between Django 1.11 and Django 3.0 to avoid complex CI configuration, but this is not my role to decide on this 🙂

**Comment by kozlek** [comment]
Finally, Django 1.11 seems to support GDAL 2.2.3 although this is not mentioned in the documentation. CI is fixed, thanks @lucacorti 😉

**Comment by alicertel** [comment]
@kozlek @lucacorti Thank you for your contributions. I will take a new release today.

**Pull request merged**
